[2024-05-17T02:49:38.418+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-05-17T02:49:38.441+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: wikipedia_flow.transform_wikipedia_data_ep1 manual__2024-05-17T02:49:18.917687+00:00 [queued]>
[2024-05-17T02:49:38.454+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: wikipedia_flow.transform_wikipedia_data_ep1 manual__2024-05-17T02:49:18.917687+00:00 [queued]>
[2024-05-17T02:49:38.454+0000] {taskinstance.py:2303} INFO - Starting attempt 1 of 1
[2024-05-17T02:49:38.473+0000] {taskinstance.py:2327} INFO - Executing <Task(PythonOperator): transform_wikipedia_data_ep1> on 2024-05-17 02:49:18.917687+00:00
[2024-05-17T02:49:38.484+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=1562) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-05-17T02:49:38.485+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'wikipedia_flow', 'transform_wikipedia_data_ep1', 'manual__2024-05-17T02:49:18.917687+00:00', '--job-id', '72', '--raw', '--subdir', 'DAGS_FOLDER/wikipedia_flow.py', '--cfg-path', '/tmp/tmpb3x4f117']
[2024-05-17T02:49:38.486+0000] {standard_task_runner.py:63} INFO - Started process 1564 to run task
[2024-05-17T02:49:38.486+0000] {standard_task_runner.py:91} INFO - Job 72: Subtask transform_wikipedia_data_ep1
[2024-05-17T02:49:38.555+0000] {task_command.py:426} INFO - Running <TaskInstance: wikipedia_flow.transform_wikipedia_data_ep1 manual__2024-05-17T02:49:18.917687+00:00 [running]> on host 85d72ecba59d
[2024-05-17T02:49:38.698+0000] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Yusuf Ganiyu' AIRFLOW_CTX_DAG_ID='wikipedia_flow' AIRFLOW_CTX_TASK_ID='transform_wikipedia_data_ep1' AIRFLOW_CTX_EXECUTION_DATE='2024-05-17T02:49:18.917687+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-05-17T02:49:18.917687+00:00'
[2024-05-17T02:49:38.700+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-05-17T02:49:51.604+0000] {connectionpool.py:824} WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Read timed out. (read timeout=10)")': /search?q=Michigan+Stadium%2C+United+States&format=json&limit=1
[2024-05-17T02:52:05.124+0000] {connectionpool.py:824} WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Read timed out. (read timeout=10)")': /search?q=Empower+Field%2C+United+States&format=json&limit=1
[2024-05-17T02:53:10.975+0000] {connectionpool.py:824} WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Read timed out. (read timeout=10)")': /search?q=Bak%C4%B1+Olimpiya+stadionu%2C+Azerbaijan&format=json&limit=1
[2024-05-17T02:54:18.598+0000] {connectionpool.py:824} WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Read timed out. (read timeout=10)")': /search?q=The+Dome%2C+United+States&format=json&limit=1
[2024-05-17T02:54:33.165+0000] {connectionpool.py:824} WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Read timed out. (read timeout=10)")': /search?q=Seoul+World+Cup+Stadium%2C+South+Korea&format=json&limit=1
[2024-05-17T02:57:35.939+0000] {connectionpool.py:824} WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Read timed out. (read timeout=10)")': /search?q=Estadio+Jalisco%2C+Mexico&format=json&limit=1
[2024-05-17T02:58:54.124+0000] {connectionpool.py:824} WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Read timed out. (read timeout=10)")': /search?q=Hrazdan+Stadium%2C+Armenia&format=json&limit=1
[2024-05-17T03:01:09.145+0000] {connectionpool.py:824} WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Read timed out. (read timeout=10)")': /search?q=%C3%9Clker+Stadyumu%2C+Turkey&format=json&limit=1
[2024-05-17T03:04:30.531+0000] {connectionpool.py:824} WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Read timed out. (read timeout=10)")': /search?q=Adrar+Stadium%2C+Morocco&format=json&limit=1
[2024-05-17T03:07:34.506+0000] {connectionpool.py:824} WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Read timed out. (read timeout=10)")': /search?q=Stade+Geoffroy-Guichard%2C+France&format=json&limit=1
[2024-05-17T03:11:54.826+0000] {warnings.py:110} WARNING - /opt/***/pipelines/wikipedia_pipeline.py:100: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  duplicates['location'] = duplicates.apply(lambda x: get_lat_long(x['country'], x['city']), axis=1)

[2024-05-17T03:11:55.918+0000] {logging_mixin.py:188} INFO -      rank  ...                                   location
0       1  ...           (39.0496732, 125.77532151186813)
1       2  ...           (42.2658652, -83.74868376764053)
2       3  ...          (40.00164575, -83.01973744224524)
3       4  ...  (-37.819908999999996, 144.98322500667754)
4       5  ...                    (41.3808046, 2.1158872)
..    ...  ...                                        ...
373   374  ...                  (22.5632358, 113.8764671)
374   375  ...                  (25.0363006, 102.7086139)
375   376  ...           (28.6496194, 121.39537897875175)
376   377  ...                  (31.1800568, 118.2141777)
377   378  ...          (23.03555805, 114.44152011468373)

[378 rows x 9 columns]
[2024-05-17T03:11:55.924+0000] {python.py:237} INFO - Done. Returned value was: OK
[2024-05-17T03:11:55.927+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-05-17T03:11:56.026+0000] {taskinstance.py:1205} INFO - Marking task as SUCCESS. dag_id=wikipedia_flow, task_id=transform_wikipedia_data_ep1, execution_date=20240517T024918, start_date=20240517T024938, end_date=20240517T031156
[2024-05-17T03:11:56.251+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-05-17T03:11:56.547+0000] {taskinstance.py:3482} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-05-17T03:11:56.553+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
