[2024-05-17T02:38:26.171+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-05-17T02:38:26.204+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: wikipedia_flow.transform_wikipedia_data_ep2 manual__2024-05-17T02:09:48.419630+00:00 [queued]>
[2024-05-17T02:38:26.216+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: wikipedia_flow.transform_wikipedia_data_ep2 manual__2024-05-17T02:09:48.419630+00:00 [queued]>
[2024-05-17T02:38:26.217+0000] {taskinstance.py:2303} INFO - Starting attempt 1 of 1
[2024-05-17T02:38:26.232+0000] {taskinstance.py:2327} INFO - Executing <Task(PythonOperator): transform_wikipedia_data_ep2> on 2024-05-17 02:09:48.419630+00:00
[2024-05-17T02:38:26.242+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=1422) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-05-17T02:38:26.243+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'wikipedia_flow', 'transform_wikipedia_data_ep2', 'manual__2024-05-17T02:09:48.419630+00:00', '--job-id', '70', '--raw', '--subdir', 'DAGS_FOLDER/wikipedia_flow.py', '--cfg-path', '/tmp/tmpm6yevbjj']
[2024-05-17T02:38:26.244+0000] {standard_task_runner.py:63} INFO - Started process 1424 to run task
[2024-05-17T02:38:26.245+0000] {standard_task_runner.py:91} INFO - Job 70: Subtask transform_wikipedia_data_ep2
[2024-05-17T02:38:26.311+0000] {task_command.py:426} INFO - Running <TaskInstance: wikipedia_flow.transform_wikipedia_data_ep2 manual__2024-05-17T02:09:48.419630+00:00 [running]> on host 85d72ecba59d
[2024-05-17T02:38:26.472+0000] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Yusuf Ganiyu' AIRFLOW_CTX_DAG_ID='wikipedia_flow' AIRFLOW_CTX_TASK_ID='transform_wikipedia_data_ep2' AIRFLOW_CTX_EXECUTION_DATE='2024-05-17T02:09:48.419630+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-05-17T02:09:48.419630+00:00'
[2024-05-17T02:38:26.475+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-05-17T02:38:26.538+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-05-17T02:38:26.540+0000] {taskinstance.py:2890} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/pipelines/wikipedia_pipeline.py", line 143, in transform_wikipedia_data_ep2
    kwargs['ti'].xcom_push(key='rows', value=data.to_json())
                                             ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/core/generic.py", line 2629, in to_json
    return json.to_json(
           ^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/json/_json.py", line 195, in to_json
    s = writer(
        ^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/json/_json.py", line 251, in __init__
    self._format_axes()
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/json/_json.py", line 315, in _format_axes
    raise ValueError(
ValueError: DataFrame columns must be unique for orient='columns'.
[2024-05-17T02:38:26.571+0000] {taskinstance.py:1205} INFO - Marking task as FAILED. dag_id=wikipedia_flow, task_id=transform_wikipedia_data_ep2, execution_date=20240517T020948, start_date=20240517T023826, end_date=20240517T023826
[2024-05-17T02:38:26.599+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 70 for task transform_wikipedia_data_ep2 (DataFrame columns must be unique for orient='columns'.; 1424)
[2024-05-17T02:38:26.621+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-05-17T02:38:26.650+0000] {taskinstance.py:3482} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-05-17T02:38:26.657+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
